# Generated by Django 5.1.6 on 2025-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_created_by_chatroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
